inputs:
  source:
    description: 'Source'
runs:
  using: "composite"
  steps:
    - name: Install packages
      run: npm install
      shell: bash
      working-directory: ${{ inputs.source}}

    # Build
    - name: Check API Definitions
      run: npm start
      shell: bash
      working-directory: ${{ inputs.source}}
