name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

  lint:
    needs: checkout
    name: API Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check API Definition
        uses: ./.github/workflows/api-lint
        with:
          source: ./tools/openapi-validator

  check-api-and-mocks:
    needs: lint
    name: Check API and Mocks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check API Definition
        uses: ./.github/workflows/check-api-and-mocks
        with:
          source-mock-server: ./mocks-servers/json-server/node
          source: ./tools/jest-openapi
